{% set name = "autopage" %}
{% set version = "0.5.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/autopage-{{ version }}.tar.gz
  sha256: 826996d74c5aa9f4b6916195547312ac6384bac3810b8517063f293248257b72

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6

test:
  imports:
    - autopage
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/zaneb/autopage
  summary: A library to provide automatic paging for console output
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - tschoonj
